from django.db import models

class Project(models.Model):
    timestamp = models.DateTimeField()
    user_email = models.EmailField()
    name = models.CharField(max_length=100)
    whatsapp = models.CharField(max_length=15, null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=100, null=True, blank=True)
    accepts_exchange = models.CharField(max_length=10, null=True, blank=True)
    worked_with_brands = models.CharField(max_length=10, null=True, blank=True)
    project_name = models.CharField(max_length=255)
    project_start_date = models.DateField()
    project_photo = models.ImageField(upload_to='project_photos/', null=True, blank=True)
    commercial_presentation = models.FileField(upload_to='presentations/', null=True, blank=True)
    metrics = models.TextField(null=True, blank=True)
    presentation_video_url = models.URLField(null=True, blank=True)
    project_website = models.URLField(null=True, blank=True)
    project_values = models.TextField(null=True, blank=True)
    project_category = models.CharField(max_length=255)
    project_sector = models.CharField(max_length=255)
    age_range = models.CharField(max_length=50)
    project_gender = models.CharField(max_length=50)
    generations = models.CharField(max_length=255)
    brand_sectors = models.CharField(max_length=255)
    reach_range = models.CharField(max_length=255)
    reach_countries = models.CharField(max_length=255)
    brand_benefits = models.TextField(null=True, blank=True)
    investment_values = models.TextField(null=True, blank=True)
    reference_code = models.CharField(max_length=50)
    tiktok_url = models.URLField(null=True, blank=True)
    instagram_url = models.URLField(null=True, blank=True)
    facebook_url = models.URLField(null=True, blank=True)
    youtube_url = models.URLField(null=True, blank=True)
    twitch_url = models.URLField(null=True, blank=True)
    kick_url = models.URLField(null=True, blank=True)
    twitter_url = models.URLField(null=True, blank=True)
    linkedin_url = models.URLField(null=True, blank=True)
    other_social_url = models.URLField(null=True, blank=True)
    unnamed_36 = models.CharField(max_length=255, null=True, blank=True)
    unnamed_37 = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.project_name
